config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'quizzes' => 'quiz#index'
  get 'quizzes/show/:id' => 'quiz#show', :as => 'quiz'
  get 'quizzes/new' => 'quiz#new'
  post 'quizzes' => 'quiz#create'
  get 'quizzes/play/:id'=> 'quiz#play', :as =>'play_quiz'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz

  validates :description, :correct_answer, :answer_option_1, :answer_option_2, :answer_option_3, presence: true, length: {maximum: 128}

  def is_correct_answer(answer)
    if answer == self.correct_answer
      true
    else
      false  
    end  
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :questions
  accepts_nested_attributes_for :questions, reject_if: proc { |attributes| attributes[:description].blank? }, allow_destroy: true
  validates :questions, :length => { :maximum => 5}

  validates :name, :category, presence: true
  validates :name, uniqueness: true
  # validates that the inputted category is one of the selectable ones.
  validates :category, :inclusion => { :in => ['Games', 'Sports', 'Music'], :message => "%{value} is not a valid category"}
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password

  validates :name, :email, presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX } 
  validates :password, presence: true, length: {minimum: 8}

  has_many :quizzes
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end 
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
    @creator = User.find(@quiz.creator_id)
  end

  def new
    @quiz = Quiz.new

   1.times { @quiz.questions.build }
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.creator_id = current_user.id

    if @quiz.save
      redirect_to root_path
    else
      render 'new'
    end    
  end

  def play
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    if params['Shuffled_Questions'] == '1'
      @questions = @questions.shuffle
    end  
  end


  private
    def quiz_params
      params.require(:quiz).permit(:name, :category, questions_attributes: [
        :description, :correct_answer, :answer_option_1, :answer_option_2, :answer_option_3])
    end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by email: params[:email]

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "Login failed. Wrong email or password."
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Registration successfull!"
      redirect_to root_path
    else
      render 'new'
    end    
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
  def link_to_add_question(name, f)
    new_object = f.object.questions.build
    fields = f.fields_for(:questions, new_object, :child_index => 'new_questions') do |builder|
      render('question_form', :f => builder)
    end
    link_to name, '', :onclick => "add_question(this, \"#{escape_javascript(fields)}\")", :remote => true
  end

  def link_to_check_answer(question, answer)
    result = question.is_correct_answer(answer)

    link_to answer, '', :onclick => "show_result(this, \"#{result}\")", :remote => true
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello</h1>

<%= link_to 'View quizzes', quizzes_path %><br>

<% if current_user %>
	<%= link_to 'Create new quiz', quizzes_new_path %>
<% else %>
	<h2>Sign in to create a quiz</h2>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="header">
  		<div id="loginField">
	  		<% if current_user %>
	  			Signed in as <%= current_user.name %> | <%= link_to 'Log out', '/logout' %>
	  		<% else %>
	  			Log in here!
	  			<%= form_tag '/login' do %>
	  				<%= text_field_tag :email, nil, placeholder: "email" %>
	  				<%= password_field_tag :password, nil, placeholder: "password" %>

	  				<%= submit_tag "Log in" %>
	  			<% end %>	
	  			Don't have an account? <%= link_to 'Register!', new_user_path %>
	  		<% end %>	
	  		
	  	</div>
	  	<%= flash.notice %>	
  	</div>
    <%= yield %>
  </body>
</html>

app/views/quiz/_form.html.erb
<script>
	$( document ).on('turbolinks:load', function() {
		$(":submit").click(function() {
			$(":text").each(function() {
				if ( $(this).val().length === 0) {
					$(this).nextAll(".error_field").first().html("<p style='color:red;'>* Field needs to be filled.</p>");
				}
			});
		});

		$("#form").on('input', ":input", function () {
			$(this).nextAll(".error_field").first().html("<p></p>");
		});

		var number_of_allowed_questions = 5
		$("#addButton").click(function() {
			if ( $(".fields:visible").length >= number_of_allowed_questions) {
				$("#addButton").hide();
			}
		});

		$("#form").on('click', ".hello", function () {
			if ( $(".fields:visible").length <= number_of_allowed_questions) {
				$("#addButton").show();
			}
		});

	});

	
</script>
<div id="form">
	<%= form_for(@quiz) do |f| %>
			<% if @quiz.errors.any? %>
				<div id="errors">
					<h2>
						<%= pluralize(@quiz.errors.count, "error") %>
						prohibited the quiz from being saved:
					</h2>

					<% @quiz.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>	
				</div>	
			<% end %>	
			
			<%= f.label :name %>
			<%= f.text_field :name, :required => true, maxlength: 128 %>
			<p class="error_field"></p>
			
			<%= f.label :category %>
			<%= f.select(:category, options_for_select(['Games', 'Sports', 'Music'], @quiz.category)) %>
			<h2>Questions</h2>
			<%= f.fields_for :questions do |ff| %>	
				<%= render 'question_form', :f => ff %>
			<% end %>
			<p id="addButton"><%= link_to_add_question "Add Question", f %></p>
			<%= f.submit %>	
	<% end %>			
</div>		

app/views/quiz/_question_form.html.erb
<div class="fields">
	<%= f.label :description %><br>
	<%= f.text_field :description, :required => true, maxlength: 128 %>
	<p class="error_field"></p>

	<%= f.label :correct_answer %><br>
	<%= f.text_field :correct_answer, :required => true, maxlength: 128 %>
	<p class="error_field"></p>

	<%= f.label :answer_option_1, "Incorrect answer 1" %><br>
	<%= f.text_field :answer_option_1, :required => true, maxlength: 128 %>
	<p class="error_field"></p>

	<%= f.label :answer_option_2, "Incorrect answer 2" %><br>
	<%= f.text_field :answer_option_2, :required => true, maxlength: 128 %>
	<p class="error_field"></p>

	<%= f.label :answer_option_3, "Incorrect answer 3" %><br>
	<%= f.text_field :answer_option_3, :required => true, maxlength: 128 %>
	<p class="error_field"></p>
	
	<p class="hello"><%= link_to "Remove Question", '', :onclick => "remove_question(this)", :remote => true %></p>
	<br>	
</div>		

app/views/quiz/index.html.erb
<%= link_to 'Back', root_path %><br>
<% @quizzes.each do |quiz| %>
	<%= link_to quiz.name, quiz_path(quiz) %>
	<b>Category:</b> <%= quiz.category %>
	<br>	
<% end %>		

app/views/quiz/new.html.erb
<script>
	$(document).ready(function(){

		
	});


</script>


<%= link_to 'Back', root_path %>

<% if current_user %>
	<h1>Create new quiz</h1>
		<%= render 'form' %>
<% else %>
	<p>sign in to be able to create a quiz</p>
<% end %>		

app/views/quiz/play.html.erb
<script>
	var score = 0;
	$( document ).on('turbolinks:load', function() {
		$(".question:not(:eq(0))").hide();
		var question_amount = $(".question").length;
		var current_question = 0;
		$(".answer").click( function(){
			$(".question:eq(" + current_question + ")").hide();
			current_question += 1
			$(".question:eq(" + current_question + ")").show();

			if (current_question == question_amount) {
				$("#score").text("Final Score: " + score);
			}
		});
		
	});
	
	function checkAns(correct_answer, answer) {
		if (correct_answer == answer) {
			score = score + 1;
			$("#score").text("Score: " + score);
		}
	}
</script>
<%= link_to 'Back', quiz_path(@quiz) %>

<% @questions.each do |question| %>
	<div class="question">
		<h2><%= question.description %></h2>

		<% array = [question.correct_answer, question.answer_option_1, question.answer_option_2, question.answer_option_3].shuffle %>

		<% array.each do |option| %>
			<!--<p class="answer"><%= link_to_check_answer question, option %></p> -->
			<%= link_to option, '', onclick: "checkAns(\"#{question.correct_answer}\", \"#{option}\")", remote: true, class: :answer %>
		<% end %>	
	</div>
<% end %>	

<div id="result"></div>

<div id="score">Score: 0</div>

app/views/quiz/show.html.erb
<%= link_to 'Back', quizzes_path %>
<h1><%= @quiz.name %></h1>
<p><b>Category:</b> <%= @quiz.category %></p>
<p><b>Number of Questions:</b> <%= @quiz.questions.count %>
<p><b>Created by:</b> <%= @creator.name %></p>

<%= form_tag("/quizzes/play/#{@quiz.id}", method: :get, enforce_utf8: false) do %>
	Shuffle Questions
	<%= check_box_tag 'Shuffled_Questions', 1, true %><br>

	<%= submit_tag 'Play', name: nil %> 
<% end %>


<!--<%= link_to "Play", play_quiz_path(@quiz) %> -->
<% if current_user == @creator %>
	Edit placeholder
<% end %>	

<h2>Comments</h2>
<h2>Rating</h2>
<h2>Highscore</h2>
<h2>First time score</h2>
<h2>First time score Friend leaderboard</h2>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for :user, url: users_path do |f| %>

	<% if @user.errors.any? %>
		<p>
			<%= pluralize(@user.errors.count, "error") %>
			prohibited the registration.
		</p>

		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>		
	<% end %>	

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>

	<%= f.submit %>
<% end %>	